index.temp.directory = /tmp
index.references.BioEntity = synonyms organism crossReferences
index.references.SequenceFeature = chromosome
index.references.OntologyTerm = synonyms
#index.references.Chromosome = assembly
#index.references.Gene = pathways proteins.proteinDomains goAnnotation.ontologyTerm
#index.references.Protein = proteinDomains

#index.ignore = AliasName Comment Consequence CrossReference Expression GOEvidence GOEvidenceCode Homologue Image Location OntologyAnnotation OntologyRelation Sequence Synonym SNV Syntelog
index.ignore = Comment Consequence CrossReference Expression GOEvidence GOEvidenceCode Homologue Image Location OntologyAnnotation OntologyRelation Sequence Synonym SNV Syntelog

index.ignore.fields = Deletion.alternateAllele Deletion.consequences Deletion.heterozygosity Deletion.referenceAllele Deletion.transcripts Deletion.validationStatus Deletion.variationType Exon.transcripts Gene.biotype GOAnnotation.annotationExtension Indel.alternateAllele Indel.consequences Indel.heterozygosity Indel.referenceAllele Indel.transcripts Indel.validationStatus Indel.variationType Insertion.alternateAllele Insertion.consequences Insertion.heterozygosity Insertion.referenceAllele Insertion.transcripts Insertion.validationStatus Insertion.variationType LncRNA.biotype MiRNA.biotype MRNA.biotype MRNA.exceptionNote MRNA.note OntologyAnnotation.dataSets OntologyAnnotation.evidence PrimaryTranscript.biotype Publication.abstractText Publication.authors Publication.crossReferences Publication.entities Publication.firstAuthor Publication.issue Publication.journal Publication.meshTerms Publication.month Publication.pages Publication.volume Publication.year RRNA.biotype SequenceAlteration.alternateAllele SequenceAlteration.consequences SequenceAlteration.referenceAllele SequenceAlteration.transcripts SequenceFeature.aliases SequenceFeature.biotype SequenceFeature.childFeatures SequenceFeature.exceptionNote SequenceFeature.note SequenceFeature.overlappingFeatures SequenceFeature.sequenceOntologyTerm SequenceFeature.status SnoRNA.biotype SnRNA.biotype Transcript.biotype Transcript.CDSs Transcript.codingSequences Transcript.exons Transcript.introns Transcript.sequenceAlterations Transcript.TSSs Transcript.UTRs TRNA.biotype TRNA.note

index.facet.single.Category = Category
index.facet.single.Organism = organism.shortName
index.facet.single.Assembly = chromosome.assembly
#index.facet.multi.Pathway = pathways.name

index.boost.Gene = 1.5
index.boost.Protein = 1.2

search.debug = false

index.solrurl = http://localhost:8983/solr/maizemine-search
index.batch.size = 1000
