//>>built
require({cache:{"JBrowse/Plugin":function(){define("JBrowse/Plugin",["dojo/_base/declare","JBrowse/Component"],function(j,b){return j(b,{constructor:function(b){this.name=b.name;this.cssLoaded=b.cssLoaded;this._finalizeConfig(b.config)},_defaultConfig:function(){return{baseUrl:"/plugins/"+this.name}}})})},"RegexSequenceSearch/View/SearchSeqDialog":function(){define("dojo/_base/declare,dojo/dom-construct,dojo/aspect,dijit/focus,dijit/form/Button,dijit/form/RadioButton,dijit/form/CheckBox,dijit/form/TextBox,JBrowse/View/Dialog/WithActionBar".split(","),
function(j,b,n,h,o,l,g,f,a){return j(a,{constructor:function(){var k=this;n.after(this,"hide",function(){h.curNode&&h.curNode.blur();setTimeout(function(){k.destroyRecursive()},500)})},_dialogContent:function(){function k(c,a){var k=b.create("label",{},a),d=(new l(c)).placeAt(k);b.create("span",{innerHTML:c.label},k);return d}var c=this.content={},a=b.create("div",{className:"search-dialog"});b.create("div",{className:"search-dialog intro",innerHTML:"This tool creates tracks showing regions of the reference sequence (or its translations) that match a given DNA or amino acid sequence."},
a);var d=b.create("div",{className:"section"},a);b.create("span",{className:"header",innerHTML:"Search for"},d);var e=b.create("div",{className:"translateContainer"},d);k({name:"translate",value:"no",label:"DNA",checked:!0},e);c.translate=k({name:"translate",value:"yes",label:"AA"},e);c.searchBox=(new f({})).placeAt(d);d=b.create("div",{className:"section"},a);e=b.create("div",{className:"checkboxdiv"},d);c.caseIgnore=new g({label:"Ignore case",id:"search_ignore_case",checked:!0});e.appendChild(c.caseIgnore.domNode);
b.create("label",{"for":"search_ignore_case",innerHTML:"Ignore Case"},e);e=b.create("div",{className:"checkboxdiv"},d);c.regex=(new g({label:"Treat as regular expression",id:"search_as_regex"})).placeAt(e);b.create("label",{"for":"search_as_regex",innerHTML:"Treat as regular expression"},e);d=b.create("div",{className:"checkboxdiv"},d);c.regex_iterate=(new g({label:"Iterate regular expression",id:"iterate_regex"})).placeAt(d);b.create("label",{"for":"iterate_regex",innerHTML:"Iterate regular expression"},
d);d=b.create("div",{className:"section"},a);b.create("span",{className:"header",innerHTML:"Search strands"},d);e=b.create("div",{className:"checkboxdiv"});c.fwdStrand=new g({id:"search_fwdstrand",checked:!0});var i=b.create("div",{className:"checkboxdiv"});c.revStrand=new g({id:"search_revstrand",checked:!0});e.appendChild(c.fwdStrand.domNode);b.create("label",{"for":"search_fwdstrand",innerHTML:"Forward"},e);i.appendChild(c.revStrand.domNode);b.create("label",{"for":"search_revstrand",innerHTML:"Reverse"},
i);d.appendChild(e);d.appendChild(i);return a},_getSearchParams:function(){var a=this.content;return{expr:a.searchBox.get("value"),regex:a.regex.checked,iterate:a.regex_iterate.checked,caseIgnore:a.caseIgnore.checked,translate:a.translate.checked,fwdStrand:a.fwdStrand.checked,revStrand:a.revStrand.checked,maxLen:100}},_fillActionBar:function(a){var c=this;(new o({label:"Search",iconClass:"dijitIconBookmark",onClick:function(){var a=c._getSearchParams();c.callback(a);c.hide()}})).placeAt(a);(new o({label:"Cancel",
iconClass:"dijitIconDelete",onClick:function(){c.callback(!1);c.hide()}})).placeAt(a)},show:function(a){this.callback=a||function(){};this.set("title","Add sequence search track");this.set("content",this._dialogContent());this.inherited(arguments);h.focus(this.closeButtonNode)}})})},"RegexSequenceSearch/Store/SeqFeature/RegexSearch":function(){define("dojo/_base/declare,dojo/_base/array,dojo/_base/lang,JBrowse/Store/SeqFeature,JBrowse/Model/SimpleFeature,JBrowse/Errors,JBrowse/Util,JBrowse/CodonTable".split(","),
function(j,b,n,h,o,l,g,f){return j(h,{constructor:function(a){this.searchParams=a.searchParams},_defaultConfig:function(){return g.deepUpdate(dojo.clone(this.inherited(arguments)),{regionSizeLimit:2E5})},getFeatures:function(a,b,c,g){var d=n.mixin({orig:{start:a.start,end:a.end}},this.searchParams,a.searchParams);if(a.end-a.start>this.config.regionSizeLimit)throw new l.DataOverflow("Region too large to search");var e=this;this.browser.getStore("refseqs",function(i){i?i.getReferenceSequence(a,function(i){e.doSearch(a,
i,d,b);c()},g):c()})},doSearch:function(a,k,c,f){var d=RegExp(c.regex?c.expr:this.escapeString(c.expr),c.caseIgnore?"gi":"g"),e=[];c.fwdStrand&&e.push([k,1]);c.revStrand&&e.push([g.revcom(k),-1]);b.forEach(e,function(b){if(c.translate)for(var e=0;3>e;e++)this._searchSequence(a,b[0],d,b[1],f,c.iterate,!0,e);else this._searchSequence(a,b[0],d,b[1],f,c.iterate)},this)},_searchSequence:function(a,b,c,g,d,e,i,f){i&&(b=this.translateSequence(b,f));for(var f=f||0,i=i?3:1,j=a.start,a=a.end,m;null!==(m=c.exec(b))&&
m.length;){c.lastIndex=m.index+1;var h=m[0],l=0<g?j+f+i*m.index:a-f-i*(m.index+h.length),n=0<g?j+f+i*(m.index+h.length):a-f-i*m.index,h=new o({data:{start:l,end:n,searchMatch:h,strand:g},id:[l,n,h].join()});d(h);if(!e)break}},translateSequence:function(a,b){for(var c=a.slice(b),c=c.slice(0,3*Math.floor(c.length/3)),g="",d=0;d<c.length;d+=3)var e=c.slice(d,d+3),g=g+f[e];return g},escapeString:function(a){return(a+"").replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1")}})})}}});
define("RegexSequenceSearch/main","dojo/_base/declare,dojo/_base/lang,dojo/Deferred,dijit/MenuItem,JBrowse/Plugin,./View/SearchSeqDialog".split(","),function(j,b,n,h,o,l){return j(o,{constructor:function(){this._searchTrackCount=0;this.browser.afterMilestone("initView",function(){this.browser.addGlobalMenuItem("file",new h({label:"Add sequence search track",iconClass:"dijitIconBookmark",onClick:b.hitch(this,"createSearchTrack")}))},this)},createSearchTrack:function(){var b=this;(new l).show(function(f){if(f){var a=
{browser:b.browser,refSeq:b.browser.refSeq,type:"RegexSequenceSearch/Store/SeqFeature/RegexSearch",searchParams:f},h=b.browser.addStoreConfig(void 0,a);a.name=h;f={type:"JBrowse/View/Track/CanvasFeatures",label:"search_track_"+b._searchTrackCount++,key:"Search reference sequence for '"+f.expr+"'",metadata:{category:"Local tracks",Description:"Contains all matches of the text string/regular expression '"+a.searchExpr+"'"},store:h};b.browser.publish("/jbrowse/v1/v/tracks/new",[f]);b.browser.publish("/jbrowse/v1/v/tracks/show",
[f])}})}})});